# Generated by Django 3.0.3 on 2020-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mark_one', models.CharField(max_length=50)),
                ('mark_two', models.CharField(max_length=50)),
                ('mark_three', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
